site_name: Team Alpha Docs
docs_dir: docs

nav:
  - Main Section in remote repository:
    - Subsection in remote repository:
      - My remote catalog: catalog.md
  - My remote catalog in nav root: catalog.md
